version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./apps/backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - ai-service
  ai-service:
    build: ./apps/ai-service
    container_name: ai-service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
volumes:
  mongo_data:
